// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace KongYingMap_Xbox
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        Int32 MyProperty;
    }
}
